modLoader="javafml"
loaderVersion="[11,)"
license="${mod_license}"
issueTrackerURL="https://morethancore.fun"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="SERVER"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},26.3)"
ordering="NONE"
side="SERVER"
